return {
  "nvim-treesitter/nvim-treesitter",
  lazy = false,
  build = ":TSUpdate",
  opts = {
    ensure_installed = {
      "python",
      "c",
      "lua",
      "vim",
      "vimdoc",
      "query",
      "rust",
      "julia",
      "cpp",
      "ocaml",
      "fsharp",
      "markdown",
      "markdown_inline",
      "yaml",
      "toml",
      "bash",
      "proto",
    },
    highlight = { enable = true },
  },
}
